db:
  image: postgres
  container_name: db

uwsgi:
  restart: always
  image: vanessa/sregistry
  container_name: uwsgi
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
  links:
    - redis
    - db

nginx:
  restart: always
  image: vanessa/sregistry_nginx
  container_name: nginx
  ports:
    - "8080:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest
  container_name: redis
  ports:
    - "6379:6379"

worker:
  image: vanessa/sregistry
  container_name: worker
  command: celery worker -A shub.celery -Q default -n default@%h -B
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
